import type { Metadata } from "next";
import { Geist, Geist_Mono, Ubuntu_Sans_Mono } from "next/font/google";
import { Sidebar } from "@/components"
import "./globals.css";

const fontSans = Ubuntu_Sans_Mono({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${fontSans.variable} antialiased`}
      >
        <div className="flex">
          <div className="flex-1/4">
            {children}
          </div>
            
          <Sidebar />
        </div>
      </body>
    </html>
  );
}
